version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tutorial-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  ngnix:
    image: nginx:1.19-alpine
    container_name: tutorial-ngnix
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d